New-Item src\inventory_api\__init__.py -ItemType File
New-Item src\inventory_api\services\__init__.py -ItemType File
New-Item src\inventory_api\routers\__init__.py -ItemType File
New-Item src\inventory_api\models.py -ItemType File
New-Item src\inventory_api\main.py -ItemType File
New-Item src\inventory_api\services\product_service.py -ItemType File
New-Item src\inventory_api\routers\products.py -ItemType File
New-Item tests\test_products_api.py -ItemType File
New-Item mkdocs.yml -ItemType File
New-Item docs\index.md -ItemType File
New-Item docs\installation.md -ItemType File
New-Item docs\reference.md -ItemType File