site_name: Inventory API
site_description: Documentation pédagogique de l'API Inventory
site_author: Equipe pédagogique

theme:
  name: material
  language: fr
  features:
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src, tests]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_if_no_docstring: false

nav:
  - Accueil: index.md
  - Installation: installation.md
  - Référence API Python: reference.md