"""Data models used by the Inventory API.

The module contains Pydantic models shared by the API routes and the
business service layer.
"""

from pydantic import BaseModel, Field


class ProductCreate(BaseModel):
    """Represent the payload required to create a product.

    Attributes:
        name: Human-readable product name.
        price: Positive product price expressed in euros.
    """

    name: str = Field(
        min_length=2,
        max_length=80,
        examples=["Sauce Labs Backpack"],
        description="Product name between 2 and 80 characters.",
    )
    price: float = Field(
        gt=0,
        examples=[29.99],
        description="Strictly positive product price.",
    )


class Product(ProductCreate):
    """Represent a product returned by the API.

    Attributes:
        id: Unique technical identifier generated by the application.
        name: Human-readable product name.
        price: Positive product price expressed in euros.
    """

    id: int = Field(
        examples=[1],
        description="Unique product identifier.",
    )